#! /usr/bin/env python3
'''
http upload cgi
This allows a user to upload up to three files at once
'''

import cgi
import cgitb
import os
import LoadNetwork

cgitb.enable()

# UPLOAD_DIR = "Uploads"
UPLOAD_DIR = "/home/nattimwin/public_html/uploaded_images"

"""This saves a file uploaded by an HTML form.
   The form_field is the name of the file input field from the form.
   For example, the following form_field would be "file_1":
       <input name="file_1" type="file">
   The upload_dir is the directory where the file will be written.
   If no file was uploaded or if the field does not exist then
   this does nothing.
"""
form = cgi.FieldStorage()
key = "image_key"
fileitem = form[key]
fout = file(os.path.join(UPLOAD_DIR, fileitem.filename), 'wb')
while 1:
    chunk = fileitem.file.read(100000)
    if not chunk:
        break
    fout.write(chunk)
fout.close()

print("Content-type:text/html\n\n")
print('peepee\n')
print(LoadNetwork.cannedResponse())

